<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    
    <xacro:include filename="intertia.xacro"/>
    <xacro:include filename="color.xacro"/>
    
    <xacro:property name="length_wheel" value="0.04"/>
    <xacro:property name="radius_wheel" value="0.07"/>
    <xacro:property name="mass_wheel" value="1"/>

    <link name="base_link">
    </link>

    <!--Defines-->
    <!--Wheel Link Definition-->
    <link name="wheel_left_front_link">
            <xacro:inertial_cylinder mass="1" length="0.04" radius="0.07">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
            </collision>
        </link>
    <link name="wheel_left_back_link">
            <xacro:inertial_cylinder mass="1" length="0.04" radius="0.07">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
            </collision>
    </link>
    <link name="wheel_right_front_link">
            <xacro:inertial_cylinder mass="1" length="0.04" radius="0.07">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
            </collision>
        </link>
    <link name="wheel_right_back_link">
            <xacro:inertial_cylinder mass="1" length="0.04" radius="0.07">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius_wheel}" length="${length_wheel}"/>
                </geometry>
            </collision>
        </link>

    <!--Joint Definition-->

   
    <link name="chasis_link">
        <xacro:inertial_box mass="10" x="0.6" y="0.3" z="0.2">
            <oigin xyz="0.0 0 0.0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0115 0.0" rpy="0.0 0.0 -1.5708"/>
            <geometry>
                <mesh filename="file://$(find rover)/description/stl/Chasis.stl" scale="0.01 0.01 0.01"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.2" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.6 0.3 0.2"/>
            </geometry>
        </collision>
    </link>

    <link name="arm_left_front_link">
           <xacro:inertial_box mass="0.2" x="0.2" y="0.2" z="0.1">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rover)/description/stl/Arm_left_front.stl" scale="0.01 0.01 0.01"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.2 0.2 0.1"/>
            </geometry>
        </collision>
    </link>

    <link name="arm_left_back_link">

            <xacro:inertial_box mass="0.2" x="0.2" y="0.2" z="0.1">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_box>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rover)/description/stl/Arm_left_back.stl" scale="0.1 0.1 0.1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.2 0.2 0.1"/>
            </geometry>
        </collision>
    </link>


    <link name="arm_right_front_link">

           <xacro:inertial_box mass="0.2" x="0.2" y="0.2" z="0.1">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_box>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rover)/description/stl/Arm_right_front.stl" scale="0.1 0.1 0.1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.2 0.2 0.1"/>
            </geometry>
        </collision>
    </link>

    <link name="arm_right_back_link">

           <xacro:inertial_box mass="0.2" x="0.2" y="0.2" z="0.1">
                <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
            </xacro:inertial_box>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rover)/description/stl/Arm_right_back.stl" scale="0.1 0.1 0.1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.2 0.2 0.1"/>
            </geometry>
        </collision>
    </link>

     <!--Chasis Definition-->
    
    <joint name="base_joint" type="fixed">
        <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chasis_link"/>
        </joint>

    <joint name="arm_left_front_joint" type="fixed">
        <origin xyz="-0.15 -0.0955 0.1" rpy="0.0 0.0 -1.5708"/>
        <parent link="chasis_link"/>
        <child link="arm_left_front_link"/>        
        
    </joint>

    <joint name="arm_left_back_joint" type="fixed">
        <origin xyz="0.17 -0.0955 0.1" rpy="3.14 0.0 -1.5708"/>
        <parent link="chasis_link"/>
        <child link="arm_left_back_link"/>        
        
    </joint>

    <joint name="arm_right_front_joint" type="fixed">
        <origin xyz="-0.15 0.0955 0.1" rpy="0.0 3.14  -1.5708"/>
        <parent link="chasis_link"/>
        <child link="arm_right_front_link"/>        
        
    </joint>

    <joint name="arm_right_back_joint" type="fixed">
        <origin xyz="0.17 0.0955 0.1" rpy="3.14 3.14  -1.5708"/>
        <parent link="chasis_link"/>
        <child link="arm_right_back_link"/>        
    </joint>

    <!--Wheel Joints Definition-->
    <joint name="wheel_left_front_joint" type="continuous"> 
        <origin xyz="${0.03+length_wheel/2} -0.067 -0.04 " rpy="3.14 -1.5708 0.0"/>
        <parent link="arm_left_front_link"/>
        <child link="wheel_left_front_link"/>
        <axis xyz="0.0 0.0 1.0"/>       
    </joint>
    <joint name="wheel_left_back_joint" type="continuous"> 
        <origin xyz="${0.03+length_wheel/2} -0.067 0.04 " rpy="3.14 -1.5708 0.0"/>
        <parent link="arm_left_back_link"/>
        <child link="wheel_left_back_link"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <joint name="wheel_right_front_joint" type="continuous"> 
        <origin xyz="${0.03+length_wheel/2} -0.067 0.04 " rpy="3.14 -1.5708 0.0"/>
        <parent link="arm_right_front_link"/>
        <child link="wheel_right_front_link"/>
        <axis xyz="0.0 0.0 1.0"/>  
    </joint>
    <joint name="wheel_right_back_joint" type="continuous"> 
        <origin xyz="${0.03+length_wheel/2} -0.067 -0.04 " rpy="3.14 -1.5708 0.0"/>
        <parent link="arm_right_back_link"/>
        <child link="wheel_right_back_link"/>
        <axis xyz="0.0 0.0 1.0"/>  
    </joint>
    
    <!--Link Definition-->


</robot>